## SCIKIT LEARNING!!!
1.Getting the data ready

A hyperparameter is a parameter that is set before the learning process begins. These parameters are tunable and can directly affect how well a model trains.

In [59]:
#Standard imports
#%matlotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [60]:
#1.Getting the data ready
import pandas as pd 
import numpy as np
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [61]:
#Create X (feature matrix)
X = heart_disease.drop("target",axis = 1)
#Create y(Labels)
y = heart_disease["target"]

In [62]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 100)
#We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [63]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2)

In [64]:
clf.fit(X_train,y_train)


RandomForestClassifier()

In [65]:
#make a prediction
y_preds = clf.predict(X_test)
y_preds

array([0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [66]:
X_train


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
220   63    0   0       150   407    0        0      154      0      4.0   
40    51    0   2       140   308    0        0      142      0      1.5   
234   70    1   0       130   322    0        0      109      0      2.4   
91    57    1   0       132   207    0        1      168      1      0.0   
285   46    1   0       140   311    0        1      120      1      1.8   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
29    53    1   2       130   197    1        0      152      0      1.2   
203   68    1   2       180   274    1        0      150      1      1.6   
178   43    1   0       120   177    0        0      120      1      2.5   
37    54    1   2       150   232    0        0      165      0      1.6   
98    43    1   2       130   315    0        1      162      0      1.9   

     slope  ca  thal  
220      1   3     3  
40       2   1     2  
234      1   3     2  
91       2   0     3  
285      1   2     3  
..     ...  ..   ...  
29       0   0     2  
203      1   0     3  
178      1   0     3  
37       2   0     3  
98       2   1     2  

[242 rows x 13 columns]

In [67]:
clf.score(X_train,y_train)

1.0

In [68]:
clf.score(X_test,y_test)

0.7868852459016393

In [69]:
y_test

179    0
135    1
176    0
166    0
3      1
      ..
85     1
24     1
54     1
274    0
290    0
Name: target, Length: 61, dtype: int64

In [70]:
y_preds

array([0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [71]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.83      0.68      0.75        28
           1       0.76      0.88      0.82        33

    accuracy                           0.79        61
   macro avg       0.79      0.78      0.78        61
weighted avg       0.79      0.79      0.78        61



In [72]:
confusion_matrix(y_test,y_preds)

array([[19,  9],
       [ 4, 29]], dtype=int64)

In [73]:
accuracy_score(y_test,y_preds)

0.7868852459016393

In [74]:
import sklearn
sklearn.show_versions()


System:
    python: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
executable: C:\Users\JOHNSON\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe
   machine: Windows-10-10.0.22621-SP0

Python dependencies:
      sklearn: 1.2.2
          pip: 23.0.1
   setuptools: 65.5.0
        numpy: 1.24.2
        scipy: 1.10.1
       Cython: None
       pandas: 1.5.3
   matplotlib: 3.7.0
       joblib: 1.2.0
threadpoolctl: 3.1.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: openblas
         prefix: libopenblas
       filepath: C:\Users\JOHNSON\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
        version: 0.3.21
threading_layer: pthreads
   architecture: Haswell
    num_threads: 8

       user_api: openmp
   internal_api: openmp
         prefix: vcomp

## Getting our data ready to be used
 Three main things we need to do:
 
        Split the data into labels and features i.e X&y  
        Filling or disregarding missing values
        Converting non - numerical values to  numerical to numerical( feature encoding)

In [75]:
#Getting the data ready
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [76]:
#We are then going to drop the target values
x = heart_disease.drop("target", axis = 1)
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [77]:
y = heart_disease["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [78]:
#Split the data into testing and training data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2)

In [79]:
x_train.shape,x_test.shape,y_test.shape,y_train.shape

((242, 13), (61, 13), (61,), (242,))

In [124]:
car_sales = pd.read_csv("car-sales.csv")

In [125]:
car_sales.head(5)

Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [126]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

## One hot encoder
Docstring:     
Encode categorical features as a one-hot numeric array.


The input to this transformer should be an array-like of integers or
strings, denoting the values taken on by categorical (discrete) features.
The features are encoded using a one-hot (aka 'one-of-K' or 'dummy')
encoding scheme. This creates a binary column for each category and
returns a sparse matrix or dense array (depending on the ``sparse_output``
parameter)


By default, the encoder derives the categories based on the unique values
in each feature. Alternatively, you can also specify the `categories`
manually.


This encoding is needed for feeding categorical data to many scikit-learn
estimators, notably linear models and SVMs with the standard kernels.


Note: a one-hot encoding of y labels should use a LabelBinarizer
instead.


In [127]:
#Turn the categories into numbers
car_sales["Price"] = car_sales["Price"].str.replace('[\$\,]|\.\d*', '').astype(int)
x = car_sales.drop("Price",axis = 1)
y = car_sales["Price"]



C:\Users\JOHNSON\AppData\Local\Temp\ipykernel_16448\3558087772.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  car_sales["Price"] = car_sales["Price"].str.replace('[\$\,]|\.\d*', '').astype(int)


In [143]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
categorical_features = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                              one_hot,
                              categorical_features)],
                          remainder = "passthrough")
transformed_x = transformer.fit_transform(x)
np.random.seed(20)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(transformed_x, y , test_size =0.2 )
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.6241488749999999

ColumnTransformer(remainder='passthrough',
                  transformers=[('one_hot', OneHotEncoder(),
                                 ['Make', 'Colour', 'Doors'])])


In [140]:
car_sales

Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White         150043      4   4000
1   Honda    Red          87899      4   5000
2  Toyota   Blue          32549      3   7000
3     BMW  Black          11179      5  22000
4  Nissan  White         213095      4   3500
5  Toyota  Green          99213      4   4500
6   Honda   Blue          45698      4   7500
7   Honda   Blue          54738      4   7000
8  Toyota  White          60000      4   6250
9  Nissan  White          31600      4   9700

In [47]:
dummies = pd.get_dummies(car_sales[["Make","Colour","Doors"]])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0      4         0           0            0            1             0   
1      4         0           1            0            0             0   
2      3         0           0            0            1             0   
3      5         1           0            0            0             1   
4      4         0           0            1            0             0   
5      4         0           0            0            1             0   
6      4         0           1            0            0             0   
7      4         0           1            0            0             0   
8      4         0           0            0            1             0   
9      4         0           0            1            0             0   

   Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0            0             0           0             1  
1            0             0           1             0  
2            1             0           0             0  
3            0             0           0             0  
4            0             0           0             1  
5            0             1           0             0  
6            1             0           0             0  
7            1             0           0             0  
8            0             0           0             1  
9            0             0           0             1

In [147]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(dummies, y , test_size =0.2 )
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.3295197482638883